// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuO2VPg0twE5t7nVcRdqEnAD5BRgLiiWg',
    appId: '1:1001143847333:web:0d1d89492af85de235404c',
    messagingSenderId: '1001143847333',
    projectId: 'maple-foudation-firebase',
    authDomain: 'maple-foudation-firebase.firebaseapp.com',
    databaseURL: 'https://maple-foudation-firebase-default-rtdb.firebaseio.com',
    storageBucket: 'maple-foudation-firebase.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbPbO7XpGoTxr_ioTnCrgxaab1DrUtLHs',
    appId: '1:1001143847333:android:790fe989b799634335404c',
    messagingSenderId: '1001143847333',
    projectId: 'maple-foudation-firebase',
    databaseURL: 'https://maple-foudation-firebase-default-rtdb.firebaseio.com',
    storageBucket: 'maple-foudation-firebase.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuO2VPg0twE5t7nVcRdqEnAD5BRgLiiWg',
    appId: '1:1001143847333:web:0d1d89492af85de235404c',
    messagingSenderId: '1001143847333',
    projectId: 'maple-foudation-firebase',
    authDomain: 'maple-foudation-firebase.firebaseapp.com',
    databaseURL: 'https://maple-foudation-firebase-default-rtdb.firebaseio.com',
    storageBucket: 'maple-foudation-firebase.firebasestorage.app',
  );
}
